import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { describe, expect, test } from "vitest";

type PackageJson = {
  version: string;
  scripts?: Record<string, string>;
};

type PackageLock = {
  version: string;
  packages: {
    "": {
      version: string;
    };
  };
};

const repoRoot = resolve(import.meta.dirname);
const scriptPath = join(repoRoot, "scripts", "sync-version.mjs");

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

function readCargoPackageVersion(path: string): string | undefined {
  const cargoToml = readFileSync(path, "utf8");

  let inPackage = false;
  for (const line of cargoToml.split(/\r?\n/)) {
    const table = line.match(/^\s*\[([^\]]+)\]/)?.[1];
    if (table) {
      inPackage = table === "package";
      continue;
    }
    if (inPackage) {
      const version = line.match(/^\s*version\s*=\s*"([^"]+)"/)?.[1];
      if (version) {
        return version;
      }
    }
  }

  return undefined;
}

function readCargoLockPackageVersion(path: string, packageName: string): string | undefined {
  const cargoLock = readFileSync(path, "utf8");
  const packageSections = cargoLock.split(/(?=^\[\[package\]\])/m);
  const packageSection = packageSections.find((section) =>
    new RegExp(`^\\s*name\\s*=\\s*"${packageName}"\\s*$`, "m").test(section),
  );

  return packageSection?.match(/^\s*version\s*=\s*"([^"]+)"/m)?.[1];
}

function writeFixture(root: string, version = "0.1.0") {
  writeFileSync(join(root, "VERSION"), `${version}\n`);
  writeFileSync(
    join(root, "package.json"),
    `${JSON.stringify({ name: "velo-fixture", version }, null, 2)}\n`,
  );
  writeFileSync(
    join(root, "package-lock.json"),
    `${JSON.stringify(
      {
        name: "velo-fixture",
        version,
        lockfileVersion: 3,
        requires: true,
        packages: {
          "": {
            name: "velo-fixture",
            version,
          },
        },
      },
      null,
      2,
    )}\n`,
  );
  writeFileSync(join(root, "Cargo.toml"), `[package]\nname = "velo-fixture"\nversion = "${version}"\n`);
  writeFileSync(
    join(root, "Cargo.lock"),
    `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "dependency"\nversion = "9.9.9"\n\n[[package]]\nname = "velo-fixture"\nversion = "${version}"\n`,
  );
}

describe("version sync config", () => {
  test("keeps VERSION, package.json, package-lock.json, and Cargo.toml aligned", () => {
    const version = readFileSync("VERSION", "utf8").trim();
    const packageJson = readJson<PackageJson>("package.json");
    const packageLock = readJson<PackageLock>("package-lock.json");
    const cargoVersion = readCargoPackageVersion("src-tauri/Cargo.toml");
    const cargoLockVersion = readCargoLockPackageVersion("src-tauri/Cargo.lock", "velo");

    expect(version).toBe("0.1.0");
    expect(packageJson.version).toBe(version);
    expect(packageLock.version).toBe(version);
    expect(packageLock.packages[""].version).toBe(version);
    expect(cargoVersion).toBe(version);
    expect(cargoLockVersion).toBe(version);
    expect(packageJson.scripts?.["version:set"]).toBe("node scripts/sync-version.mjs");
    expect(existsSync(scriptPath)).toBe(true);
  });

  test("sync script updates fixture files to the requested version", () => {
    const fixtureRoot = mkdtempSync(join(tmpdir(), "velo-version-sync-"));

    try {
      writeFixture(fixtureRoot);

      const result = spawnSync(process.execPath, [scriptPath, "1.2.3"], {
        cwd: fixtureRoot,
        encoding: "utf8",
      });

      expect(result.status).toBe(0);
      expect(readFileSync(join(fixtureRoot, "VERSION"), "utf8")).toBe("1.2.3\n");
      expect(readJson<PackageJson>(join(fixtureRoot, "package.json")).version).toBe("1.2.3");
      const packageLock = readJson<PackageLock>(join(fixtureRoot, "package-lock.json"));
      expect(packageLock.version).toBe("1.2.3");
      expect(packageLock.packages[""].version).toBe("1.2.3");
      expect(readCargoPackageVersion(join(fixtureRoot, "Cargo.toml"))).toBe("1.2.3");
      expect(readCargoLockPackageVersion(join(fixtureRoot, "Cargo.lock"), "velo-fixture")).toBe(
        "1.2.3",
      );
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  test("sync script reads VERSION when no version argument is provided", () => {
    const fixtureRoot = mkdtempSync(join(tmpdir(), "velo-version-sync-"));

    try {
      writeFixture(fixtureRoot, "2.0.0");
      writeFileSync(
        join(fixtureRoot, "package.json"),
        `${JSON.stringify({ name: "velo-fixture", version: "0.0.1" }, null, 2)}\n`,
      );

      const result = spawnSync(process.execPath, [scriptPath], {
        cwd: fixtureRoot,
        encoding: "utf8",
      });

      expect(result.status).toBe(0);
      expect(readJson<PackageJson>(join(fixtureRoot, "package.json")).version).toBe("2.0.0");
      expect(readCargoPackageVersion(join(fixtureRoot, "Cargo.toml"))).toBe("2.0.0");
      expect(readCargoLockPackageVersion(join(fixtureRoot, "Cargo.lock"), "velo-fixture")).toBe(
        "2.0.0",
      );
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  test("sync script rejects invalid versions without mutating fixture files", () => {
    const fixtureRoot = mkdtempSync(join(tmpdir(), "velo-version-sync-"));

    try {
      writeFixture(fixtureRoot);

      const result = spawnSync(process.execPath, [scriptPath, "1.2"], {
        cwd: fixtureRoot,
        encoding: "utf8",
      });

      expect(result.status).not.toBe(0);
      expect(result.stderr).toContain("Invalid version");
      expect(readFileSync(join(fixtureRoot, "VERSION"), "utf8")).toBe("0.1.0\n");
      expect(readJson<PackageJson>(join(fixtureRoot, "package.json")).version).toBe("0.1.0");
      const packageLock = readJson<PackageLock>(join(fixtureRoot, "package-lock.json"));
      expect(packageLock.version).toBe("0.1.0");
      expect(packageLock.packages[""].version).toBe("0.1.0");
      expect(readCargoPackageVersion(join(fixtureRoot, "Cargo.toml"))).toBe("0.1.0");
      expect(readCargoLockPackageVersion(join(fixtureRoot, "Cargo.lock"), "velo-fixture")).toBe(
        "0.1.0",
      );
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  test("sync script enforces strict semver without numeric leading zeros", () => {
    const fixtureRoot = mkdtempSync(join(tmpdir(), "velo-version-sync-"));

    try {
      writeFixture(fixtureRoot);

      for (const version of ["01.2.3", "1.02.3", "1.2.03", "1.2.3-01"]) {
        const result = spawnSync(process.execPath, [scriptPath, version], {
          cwd: fixtureRoot,
          encoding: "utf8",
        });

        expect(result.status).not.toBe(0);
        expect(result.stderr).toContain("Invalid version");
      }

      expect(readFileSync(join(fixtureRoot, "VERSION"), "utf8")).toBe("0.1.0\n");
      expect(readJson<PackageJson>(join(fixtureRoot, "package.json")).version).toBe("0.1.0");
      expect(readCargoPackageVersion(join(fixtureRoot, "Cargo.toml"))).toBe("0.1.0");
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  test("sync script accepts prerelease and build semver metadata", () => {
    const fixtureRoot = mkdtempSync(join(tmpdir(), "velo-version-sync-"));

    try {
      writeFixture(fixtureRoot);

      const result = spawnSync(process.execPath, [scriptPath, "1.2.3-beta.1+build.1"], {
        cwd: fixtureRoot,
        encoding: "utf8",
      });

      expect(result.status).toBe(0);
      expect(readFileSync(join(fixtureRoot, "VERSION"), "utf8")).toBe("1.2.3-beta.1+build.1\n");
      expect(readJson<PackageJson>(join(fixtureRoot, "package.json")).version).toBe(
        "1.2.3-beta.1+build.1",
      );
      expect(readCargoPackageVersion(join(fixtureRoot, "Cargo.toml"))).toBe(
        "1.2.3-beta.1+build.1",
      );
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  test("sync script only updates package version within Cargo.toml table boundaries", () => {
    const fixtureRoot = mkdtempSync(join(tmpdir(), "velo-version-sync-"));

    try {
      writeFixture(fixtureRoot);
      writeFileSync(
        join(fixtureRoot, "Cargo.toml"),
        `[package]\nname = "velo-fixture"\n# keep this comment\n version = "0.1.0" # package version\n\n[package.metadata]\nversion = "do-not-touch"\n`,
      );

      const result = spawnSync(process.execPath, [scriptPath, "3.4.5"], {
        cwd: fixtureRoot,
        encoding: "utf8",
      });
      const cargoToml = readFileSync(join(fixtureRoot, "Cargo.toml"), "utf8");

      expect(result.status).toBe(0);
      expect(readCargoPackageVersion(join(fixtureRoot, "Cargo.toml"))).toBe("3.4.5");
      expect(cargoToml).toContain(' version = "3.4.5" # package version');
      expect(cargoToml).toContain('[package.metadata]\nversion = "do-not-touch"');
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });

  test("sync script does not mutate files when Cargo.toml lacks package version", () => {
    const fixtureRoot = mkdtempSync(join(tmpdir(), "velo-version-sync-"));

    try {
      writeFixture(fixtureRoot);
      writeFileSync(join(fixtureRoot, "Cargo.toml"), `[package]\nname = "velo-fixture"\n`);
      const before = {
        version: readFileSync(join(fixtureRoot, "VERSION"), "utf8"),
        packageJson: readFileSync(join(fixtureRoot, "package.json"), "utf8"),
        packageLock: readFileSync(join(fixtureRoot, "package-lock.json"), "utf8"),
        cargoToml: readFileSync(join(fixtureRoot, "Cargo.toml"), "utf8"),
        cargoLock: readFileSync(join(fixtureRoot, "Cargo.lock"), "utf8"),
      };

      const result = spawnSync(process.execPath, [scriptPath, "3.4.5"], {
        cwd: fixtureRoot,
        encoding: "utf8",
      });

      expect(result.status).not.toBe(0);
      expect(result.stderr).toContain("Cargo manifest");
      expect(readFileSync(join(fixtureRoot, "VERSION"), "utf8")).toBe(before.version);
      expect(readFileSync(join(fixtureRoot, "package.json"), "utf8")).toBe(before.packageJson);
      expect(readFileSync(join(fixtureRoot, "package-lock.json"), "utf8")).toBe(before.packageLock);
      expect(readFileSync(join(fixtureRoot, "Cargo.toml"), "utf8")).toBe(before.cargoToml);
      expect(readFileSync(join(fixtureRoot, "Cargo.lock"), "utf8")).toBe(before.cargoLock);
    } finally {
      rmSync(fixtureRoot, { recursive: true, force: true });
    }
  });
});
